name: 'Auto Release Draft'
description: 'Drafts a GitHub release with the changes introduced by a newly created version tag'
author: 'Himanshu Tiwari'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

inputs:
  repo-token:
    description: 'The GITHUB_TOKEN used to authenticate'
    required: true

# Define your outputs here.
outputs:
  release-url:
    description: 'The URL of the Github release that was drafted'

runs:
  using: node20
  main: dist/index.js
